// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/liquid-glass/DarkVariant.tsx": () => import("../components/mockups/liquid-glass/DarkVariant.tsx"),
  "./components/mockups/liquid-glass/LightVariant.tsx": () => import("../components/mockups/liquid-glass/LightVariant.tsx")
};
